[versions]
agp = "8.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
navigation = "2.9.5"
secrets = "2.0.1"
location = "21.3.0"
maps = "3.19.0"
room = "2.8.3"
preference = "1.2.1"
volley = "1.2.1"
spotifyAuth = "3.0.0"
download = "5.6.0"
gson = "2.13.2"

spotifyAppRemoteUrl = "https://github.com/spotify/android-sdk/releases/download/v0.8.0-appremote_v2.1.0-auth/spotify-app-remote-release-0.8.0.aar"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "location" }
android-maps-utils = { group = "com.google.maps.android", name = "android-maps-utils", version.ref = "maps" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
spotify-android-auth = { group = "com.spotify.android", name = "auth", version.ref = "spotifyAuth" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
androidx-room = { id = "androidx.room", version.ref = "room" }
download = { id = "de.undercouch.download", version.ref = "download" }
